mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    #path('login/',views.user_login, name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name= 'user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
]

mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include('account.urls', namespace='account')),

]

mysite/account/models.py
from django.db import models

# Create your models here.

mysite/blog/models.py
from django.db import models

# Create your models here.

#from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

mysite/account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput)

class RegistrationForm(forms.ModelForm):
	password = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("username", "email")

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError("passwords do not match.")
		return cd['password2']

mysite/account/views.py
# from django.shortcuts import render
# from django.http import HttpResponse
# from django.contrib.auth import authenticate,login
# from .forms import LoginForm
#
# def user_login(request):
#     if request.method == "POST":
#         login_form = LoginForm(request.POST)
#         if login_form.is_valid():
#             cd = login_form.cleaned_data
#             user = authenticate(username=cd['username'], password = cd["password"])
#
#             if user:
#                 login(reques,user)
#                 return HttpResponse("Welcome You! You have been aythenticated successfully")
#             else:
#                 return HttpResponse("Sorry. Your username or password is incorrect.")
#         else:
#             return HttpResponse("Invalid login")
#     if request.method == "GET":
#         login_form = LoginForm()
#         return render(request, 'account/login.html', {"form": login_form})

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from .forms import LoginForm

def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd =login_form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])

            if user:
                login(request,user)
                return HttpResponse("Welcome You! You have been aythenticated successfully")
            else:
                return HttpResponse("Sorry. Your username or password is not right.")
        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request,"account/login.html",{"form":login_form})

from .forms import LoginForm, RegistrationForm

def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry, you can not register.")
    else:
        user_form = RegistrationForm()
        return render(request, "account/register.html",{"form": user_form})

mysite/blog/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404
from .models import BlogArticles

def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html",{"blogs":blogs})
def blog_article(request, article_id):
    article = BlogArticles.objects.get(id=article_id)
    aritcle = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/content.html",{"article":article, "publish":pub })

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}{% endblock %}
    </body>
</html>

mysite/templates/blog/content.html
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
  <h1>{{ article.title }}</h1>
</div>
<div class="row">
  <div class="col-xs-122 col-md-8">
    <p class="text-center"><span>{{ article.author.username }}
      </span><span style="margin-left: 20px">{{ publish}}</span>
    </p>
<div>{{ article.body }}</div>
</div>
  <div class="col-xs-6 col-md-4">
    <h2>AD</h2>
    <p>Qi:www.itdiffer.com</p>
    <img width="200px" src="https://raw.githubusercontent.com/qiwsir/DjangoPracticeProject/master/python-book2.png">
  </div>
</div>
{% endblock %}

mysite/templates/blog/title.html
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
  <h1>My Blog</h1>
</div>
<div class="row">
  <div class="col-xs-12 col-md-8">
  <ul>
  {% for blog in blogs %}
    <li><a href="{{ blog.id }}">{{blog.title}}</a></li>
    {% endfor %}
  </ul>
  </div>
  <div class="col-xs-6 col-md-4">
  <h2>AD</h2>
  <p>Qi:www.itdiffer.com</p>
  <img width="200px" src="https://raw.githubusercontent.com/qiwsir/DjangoPracticeProject/master/python-book2.png">
  </div>
</div>
{% endblock %}

mysite/templates/blog/titles.html
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
  <h1>My Blog</h1>
</div>
<div class="row">
  <div class="col-xs-12 col-md-8">
  <ul>
  {% for blog in blogs %}
    <li><a href="{{ blog.id }}">{{blog.title}}</a></li>
    {% endfor %}
  </ul>
  </div>
  <div class="col-xs-6 col-md-4">
  <h2>AD</h2>
  <p>Qi:www.itdiffer.com</p>
  <img width="200px" src="https://raw.githubusercontent.com/qiwsir/DjangoPracticeProject/master/python-book2.png">
  </div>
</div>
{% endblock %}

mysite/templates/footer.html
<div class="container">
	<hr>
	<p class="text-center">copy right www.purdawn.com</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class= "navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/logo.svg' %}" width="100px">
            </a>
            
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a>  
                </li>
                {% endif %}
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                <li><a href="{% url 'account:user_register' %}">REGISTER</a>  
                </li>
            </ul>
        </div>
        
    </nav>
</div>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>Document</title>

    <link rel="stylesheet" href="{% static'css/bootstrap.css' %}">

    <script src="{% static'js/jquery.js %}"></script>

</head>
<body>
    <div style="margin:0 auto;width:200px;">
    <input type="submit" value="Login" style="vertical-align:middle;">
    </div>
</body>
</html>